### PR TITLE
Guess and Check

### PR DESCRIPTION
**Pull request by qliu17**
FlowGraph : Guess and Check
[LoAT-Guess&Check.zip](https://github.com/mttnff/LoAT/files/1126487/LoAT-Guess.Check.zip)

### CODE REVIEW

**Comment by mttnff** [comment]
This repo has been moved to [aprove-developers/LoAT](<https://github.com/aprove-developers/LoAT>), please post your pull request there.

**Comment by mttnff** [comment]
I've tried to merge the code from your zipfile into a new branch of [aprove-developers/LoAT](<https://github.com/aprove-developers/LoAT>). Unfortunately, your code is based on the old version (this repo) instead of the current version of LoAT, which lead to several conflicts. It would be helpful if you could check that your implementation is used correctly in the merged branch:  [guess-and-check_merge](<https://github.com/aprove-developers/LoAT/tree/guess-and-check_merge>).

**Comment by qliu17** [comment]
Hi Matthias,

    thanks for you email. Is it okay if I check the source code and compile
again this weekend? Because I'm currently working on weekdays. Sorry for
the inconvenience!

    Best,

    Liu

2017-08-08 18:59 GMT+08:00 Matthias Naaf <notifications@github.com>:

**Comment by mttnff** [comment]
Yes, that would be nice. Since your code appears to be based on the old version, it would be nice to know whether the merge worked and also whether your improvements still work. In the current version of LoAT, the core technique of chaining and accelerating was slightly changed to better match up the description in the paper. This _might_ affect some of your improvements.

To avoid confusion, there are currently two branches with your code:

- [guess-and-check_merge](<https://github.com/aprove-developers/LoAT/tree/guess-and-check_merge>): as mentioned above, my attempt to merge your code with the current version. This is the interesting one.
- [guess-and-check_original](<https://github.com/aprove-developers/LoAT/tree/guess-and-check_original>): this branch is based on an old commit and contains your code without changes.

**Comment by qliu17** [comment]
Hi Matthias,

    I didn't have enough time for solving the merge problem last weekend. I
think next weekend I'll have more time. This friday I have a deadline for
coding and writing document, which is kind of stressful for me. Sorry for
the delay!

    Liu

2017-08-11 19:07 GMT+08:00 Matthias Naaf <notifications@github.com>:

**Pull request closed without merging**
